# Generated by Django 4.2.4 on 2024-01-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=200)),
                ('porcentaje', models.FloatField()),
                ('ficha', models.IntegerField()),
            ],
        ),
    ]
